language: r
sudo: false
cache: packages
r_packages:
- knitr
- covr
- drat
r_github_packages:
- cloudyr/aws.iam
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
    secure: AXqHFBcuu6L6GqrtxICv1RyReoGs/4yCq6D7yXjZYUI4xJ0bYjB4vnmIn6hH1yt+xGqIOI5ApZfkeOLE7QkA9vrB51SBMvBi+sgLLuuItwywh4RHgV6Fwaa0bX4hiGgYnubvAvVD7psUZRcJvFpTEq2G3g99HDtbE5vx7/H4x/k=
